/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cocktailapp;

import DBloggers.DBcocktailApp;
import Exceptions.BlenderEmptyException;
import Exceptions.BlenderOverFlowException;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author actc
 */
public class JCocktail extends javax.swing.JFrame {

    private ArrayList<Fruits> fruits;
    private ArrayList<Fruits> addedFruits=new ArrayList<>(); 
    private ArrayList<Ingredients> milk;
    private ArrayList<Ingredients> addedMilk;
    private ArrayList<Ingredients> addedSugar = new ArrayList<>();
    private int totalCalories = 0;
    private int totalVolume = 0;
    private int sugarVolume = 0;
    private final int smallCup = 100;
    private final int mediumCup = 150;
    private final int largeCup = 200;
    private final int blenderCapacity = 1200;
    private int blenderVolume;

//       private Sugar[] sugars = {
//        new Sugar("No Sugar", 0, 0, null),
//        new Sugar("One Spoon", 16, 5, Color.WHITE),
//        new Sugar("Two Spoons", 32, 10, Color.WHITE)
//    };

    /**
     * Creates new form JCocktail
     */
//    void display() {
//        String[] names = new String[addedFruits.size()];
//        for (int i = 0; i < addedFruits.size(); i++) {
//            names[i] = addedFruits.get(i).getName();
//        }
//        blenderInfojList1.setListData(names);
//    }
    
//    void display1() {
//        String[] names = new String[addedMilk.size()];
//        for (int i = 0; i < addedMilk.size(); i++) {
//            names[i] = addedMilk.get(i).getName();
//        }
//        
//        blenderInfojList1.setListData(names);
//    }
    
     void display() {
        String[] names = new String[addedFruits.size()];
        for (int i = 0; i < addedFruits.size(); i++) {
            names[i] = addedFruits.get(i).getName();
        }
        blenderInfojList1.setListData(names);
    }

    void display1() {
        String[] names = new String[addedMilk.size()];
        for (int i = 0; i < addedMilk.size(); i++) {
            names[i] = addedMilk.get(i).getName();
        }
        blenderInfojList1.setListData(names);
    }
    private void displaySugar() {
    String[] names = new String[addedSugar.size()];
    for (int i = 0; i < addedSugar.size(); i++) {
        names[i] = addedSugar.get(i).getName();
    }
    blenderInfojList1.setListData(names);
}

    
    public JCocktail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSize = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        fruitPanel = new javax.swing.JPanel();
        jComboBoxFruit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fruitVolumeTextField = new javax.swing.JTextField();
        addFruitsButton = new javax.swing.JButton();
        milkPanel = new javax.swing.JPanel();
        milkComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        milkVolumeTextField = new javax.swing.JTextField();
        addMilkButton = new javax.swing.JButton();
        cupSizePanel = new javax.swing.JPanel();
        smallRadioButton1 = new javax.swing.JRadioButton();
        mediumRadioButton2 = new javax.swing.JRadioButton();
        largeRadioButton3 = new javax.swing.JRadioButton();
        sugatPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sugarVolumeTextField = new javax.swing.JTextField();
        addSugarButton = new javax.swing.JButton();
        sugarSlider1 = new javax.swing.JSlider();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pourButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        blenderInfojList1 = new javax.swing.JList<>();
        historyPanel = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePanel.setBackground(new java.awt.Color(255, 232, 232));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/92611380590.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(568, 439));

        jLabel8.setFont(new java.awt.Font("Constantia", 3, 48)); // NOI18N
        jLabel8.setText("  Cocktail Market");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("START");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel13.setText("Welcome to Cocktail Master! ");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/◯ ༚_° [+✩‧₊˚ ⭑_1.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel15.setText("Discover and mix the perfect drink with our easy recipes and tips.");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/◯ ༚_° [+✩‧₊˚ ⭑_1.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/◯ ༚_° [+✩‧₊˚ ⭑_1.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/◯ ༚_° [+✩‧₊˚ ⭑_1.png"))); // NOI18N

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)))
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", homePanel);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setBounds(new java.awt.Rectangle(0, 1, 2, 3));

        fruitPanel.setBackground(new java.awt.Color(153, 128, 135));
        fruitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fruits", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N

        jComboBoxFruit.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxFruit.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jComboBoxFruit.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxFruit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Banana", "Orange", "Kiwi", "Pineapple" }));
        jComboBoxFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFruitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("volume");

        fruitVolumeTextField.setBackground(new java.awt.Color(255, 255, 255));

        addFruitsButton.setBackground(new java.awt.Color(255, 255, 255));
        addFruitsButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        addFruitsButton.setForeground(new java.awt.Color(51, 51, 51));
        addFruitsButton.setText("Add");
        addFruitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFruitsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fruitPanelLayout = new javax.swing.GroupLayout(fruitPanel);
        fruitPanel.setLayout(fruitPanelLayout);
        fruitPanelLayout.setHorizontalGroup(
            fruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fruitPanelLayout.createSequentialGroup()
                .addGroup(fruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fruitPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fruitPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fruitVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fruitPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(addFruitsButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        fruitPanelLayout.setVerticalGroup(
            fruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fruitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxFruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fruitVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addFruitsButton))
        );

        jComboBoxFruit.getAccessibleContext().setAccessibleDescription("");

        milkPanel.setBackground(new java.awt.Color(153, 128, 135));
        milkPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Milk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N

        milkComboBox.setBackground(new java.awt.Color(255, 255, 255));
        milkComboBox.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        milkComboBox.setForeground(new java.awt.Color(51, 51, 51));
        milkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cow's Milk", "Almond Milk" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("volume");

        milkVolumeTextField.setBackground(new java.awt.Color(255, 255, 255));

        addMilkButton.setBackground(new java.awt.Color(255, 255, 255));
        addMilkButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        addMilkButton.setForeground(new java.awt.Color(51, 51, 51));
        addMilkButton.setText("Add");
        addMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMilkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout milkPanelLayout = new javax.swing.GroupLayout(milkPanel);
        milkPanel.setLayout(milkPanelLayout);
        milkPanelLayout.setHorizontalGroup(
            milkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(milkPanelLayout.createSequentialGroup()
                .addGroup(milkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(milkPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(milkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(milkPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(milkVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(milkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(milkPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(addMilkButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        milkPanelLayout.setVerticalGroup(
            milkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(milkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(milkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(milkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(milkVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMilkButton))
        );

        cupSizePanel.setBackground(new java.awt.Color(153, 128, 135));
        cupSizePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cocktail Cup Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        cupSizePanel.setForeground(new java.awt.Color(255, 255, 255));

        smallRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSize.add(smallRadioButton1);
        smallRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        smallRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        smallRadioButton1.setText("Small");
        smallRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallRadioButton1ActionPerformed(evt);
            }
        });

        mediumRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSize.add(mediumRadioButton2);
        mediumRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        mediumRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        mediumRadioButton2.setText("Medium");

        largeRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSize.add(largeRadioButton3);
        largeRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        largeRadioButton3.setForeground(new java.awt.Color(51, 51, 51));
        largeRadioButton3.setText("Large");

        javax.swing.GroupLayout cupSizePanelLayout = new javax.swing.GroupLayout(cupSizePanel);
        cupSizePanel.setLayout(cupSizePanelLayout);
        cupSizePanelLayout.setHorizontalGroup(
            cupSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cupSizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(smallRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mediumRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(largeRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cupSizePanelLayout.setVerticalGroup(
            cupSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cupSizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cupSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallRadioButton1)
                    .addComponent(mediumRadioButton2)
                    .addComponent(largeRadioButton3))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        mediumRadioButton2.getAccessibleContext().setAccessibleName("size");
        largeRadioButton3.getAccessibleContext().setAccessibleName("size");

        sugatPanel.setBackground(new java.awt.Color(153, 128, 135));
        sugatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sugar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("volume");

        sugarVolumeTextField.setBackground(new java.awt.Color(255, 255, 255));

        addSugarButton.setBackground(new java.awt.Color(255, 255, 255));
        addSugarButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        addSugarButton.setForeground(new java.awt.Color(51, 51, 51));
        addSugarButton.setText("Add");
        addSugarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSugarButtonActionPerformed(evt);
            }
        });

        sugarSlider1.setBackground(new java.awt.Color(204, 255, 204));
        sugarSlider1.setForeground(new java.awt.Color(255, 255, 255));
        sugarSlider1.setMajorTickSpacing(1);
        sugarSlider1.setMaximum(10);
        sugarSlider1.setPaintLabels(true);
        sugarSlider1.setPaintTicks(true);

        javax.swing.GroupLayout sugatPanelLayout = new javax.swing.GroupLayout(sugatPanel);
        sugatPanel.setLayout(sugatPanelLayout);
        sugatPanelLayout.setHorizontalGroup(
            sugatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sugatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sugatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sugatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addSugarButton)
                        .addGroup(sugatPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sugarVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sugarSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        sugatPanelLayout.setVerticalGroup(
            sugatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sugatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sugatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sugarVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sugarSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSugarButton))
        );

        jPanel8.setBackground(new java.awt.Color(153, 128, 135));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blender Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blendercapacity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16), new java.awt.Color(51, 51, 51))); // NOI18N

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(153, 128, 135));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("1000 ml");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("MAX");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cups capacity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16), new java.awt.Color(51, 51, 51))); // NOI18N

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(153, 128, 135));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("100 ml");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Small");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(153, 128, 135));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("200 ml");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Large");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Medium");

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(153, 128, 135));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("150 ml");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Strawberry free icons designed by Freepik.png"))); // NOI18N

        jLabel11.setDisplayedMnemonic('1');
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/#fruit #food #fruits #watermelon #fruity #freetoedit.png"))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(153, 128, 135));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 4));

        jLabel12.setBackground(new java.awt.Color(153, 128, 135));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cocktail Market");
        jLabel12.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel12AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Blend Ingredients");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pourButton.setBackground(new java.awt.Color(204, 255, 204));
        pourButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        pourButton.setForeground(new java.awt.Color(51, 51, 51));
        pourButton.setText("Pour into cup/s");
        pourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pourButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blender Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        blenderInfojList1.setBackground(new java.awt.Color(153, 128, 135));
        jScrollPane1.setViewportView(blenderInfojList1);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11))
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cupSizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sugatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(29, 29, 29)
                                        .addComponent(pourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fruitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(milkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(cupSizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fruitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(milkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(sugatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(pourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu", menuPanel);
        menuPanel.getAccessibleContext().setAccessibleName("Menu");
        menuPanel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("History", historyPanel);

        jMenu3.setText("File");

        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("Open");
        jMenu3.add(jMenuItem3);
        jMenu3.add(jSeparator1);

        jMenuItem4.setText("Close");
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu4.add(jMenuItem2);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Menu");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void smallRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallRadioButton1ActionPerformed

    private void addMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMilkButtonActionPerformed
       if (addedMilk == null) {
        addedMilk = new ArrayList<>();
    }
       milk = new ArrayList<>();
        milk.add(new Milk("Cow's Milk", 42, 100));
        milk.add(new Milk("Almond Milk", 17, 100));
//    initializeIngredientsMilk();
//       populatemilkComboBoxes();
        try {
            int selectedIndex = milkComboBox.getSelectedIndex();
            if (selectedIndex == -1) {
                throw new Exception("No milk type selected!");
            }
             ;
        //    milk.get(selectedIndex);
            String name = milkComboBox.getSelectedItem().toString();
            int milkVolume = Integer.parseInt(milkVolumeTextField.getText());
            int milkCalories = ((milk.get(selectedIndex).getCalories()) * milkVolume) / milk.get(selectedIndex).getVolume();
            Milk m = new Milk(name, milkVolume, milkCalories);
            addedMilk.add(m);
            display1();
            milkVolumeTextField.setText("");
            
        //    listModel.addElement(name);
        
            milk.get(selectedIndex).setCalories(milkCalories);
            totalCalories += milk.get(selectedIndex).getCalories();
            totalVolume += milk.get(selectedIndex).getVolume();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_addMilkButtonActionPerformed

    private void addFruitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFruitsButtonActionPerformed
        fruits = new ArrayList<>();
        fruits.add(new Fruits("Apple", 52, 100, new Color(144, 238, 144)));
        fruits.add(new Fruits("Banana", 89, 100, new Color(255, 255, 0)));
        fruits.add(new Fruits("Orange", 47, 100, new Color(255, 165, 0)));
        fruits.add(new Fruits("Kiwi", 61, 100, new Color(142, 229, 63)));
        fruits.add(new Fruits("Pineapple", 50, 100, new Color(255, 224, 102)));
//         populatefruitComboBoxes();
        try {
            int selectedIndex = jComboBoxFruit.getSelectedIndex();
            if (selectedIndex == -1) {
                throw new Exception("No fruit selected!");
            }

//           fruits.get(selectedIndex)
            String name = jComboBoxFruit.getSelectedItem().toString();
            int fruitVolume = Integer.parseInt(fruitVolumeTextField.getText());
            int fruitCalories = ((fruits.get(selectedIndex).getCalories()) * fruitVolume) / fruits.get(selectedIndex).getVolume();
            int redColor = fruits.get(selectedIndex).getColor().getRed();
            int greenColor = fruits.get(selectedIndex).getColor().getGreen();
            int blueColor = fruits.get(selectedIndex).getColor().getBlue();
            Color color = new Color(redColor, greenColor, blueColor);
            Fruits f = new Fruits(name, fruitCalories, fruitVolume, color);
            addedFruits.add(f);
            display();
            fruitVolumeTextField.setText("");
//           new code above

            fruits.get(selectedIndex).setCalories(fruitCalories);
            totalCalories += fruits.get(selectedIndex).getCalories();
            totalVolume += fruits.get(selectedIndex).getVolume();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_addFruitsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        //        Cocktail cocktail = new Cocktail();
//        String data = cocktail.getInfo();
          DBcocktailApp db = new DBcocktailApp();
//        db.log(blenderInfo);
//        db.log(data);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel12AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12AncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // Check if the total volume exceeds the blender's capacity
            if (totalVolume > blenderCapacity) {
                throw new Exception("Total volume exceeds blender capacity!");
            }

            // Calculate the combined color
            int totalRed = 0, totalGreen = 0, totalBlue = 0;
            int totalCombinedVolume = 0;

            for (Fruits fruit : addedFruits) {
                totalRed += fruit.getColor().getRed() * fruit.getVolume();
                totalGreen += fruit.getColor().getGreen() * fruit.getVolume();
                totalBlue += fruit.getColor().getBlue() * fruit.getVolume();
                totalCombinedVolume += fruit.getVolume();
            }

            for (Ingredients milk : addedMilk) {
                // Assuming milk is white for simplicity
                totalRed += milk.getVolume() * 255; // White has RGB (255, 255, 255)
                totalGreen += milk.getVolume() * 255;
                totalBlue += milk.getVolume() * 255;
                totalCombinedVolume += milk.getVolume();
            }

            // Add sugar to the combined volume (sugar is white with RGB (255, 255, 255))
            totalRed += sugarVolume * 255;
            totalGreen += sugarVolume * 255;
            totalBlue += sugarVolume * 255;
            totalCombinedVolume += sugarVolume;

            if (totalCombinedVolume > 0) {
                totalRed /= totalCombinedVolume;
                totalGreen /= totalCombinedVolume;
                totalBlue /= totalCombinedVolume;
            }

            Color combinedColor = new Color(totalRed, totalGreen, totalBlue);

            // Display the blender information
            String[] blenderInfo = new String[4];
            blenderInfo[0] = "Total Calories: " + totalCalories;
            blenderInfo[1] = "Total Volume: " + totalVolume + " mL";
            blenderInfo[2] = "Combined Color: RGB(" + totalRed + ", " + totalGreen + ", " + totalBlue + ")";
            blenderInfo[3] = "Number of Sugar Spoons: " + sugarSlider1.getValue();

            blenderInfojList1.setListData(blenderInfo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
//        Ingredients selectedMilk = milks[milkComboBox.getSelectedIndex()];
//
//        double totalCalories = 0;
//        int totalVolume = 0;
//        for (Blender blender : arr) {
//            totalCalories += blender.getCalories();
           // totalVolume += blender.getVolume();

            /*switch (fruitsComboBox.getSelectedItem().toString()) {
           case "pineapple":
                int fruitvolume = Integer.parseInt(fruitVolumeTextField.getText());
                double calories =  ((50*Integer.parseInt(fruitVolumeTextField.getText()))/100.0);
                Blender b=new Blender(calories,new Color(255, 224, 102), fruitvolume);
                
                 arr.add(b);
            case "kiwi":
               int fruitvolume1 = Integer.parseInt(fruitVolumeTextField.getText());
                double calories1 =  ((61*Integer.parseInt(fruitVolumeTextField.getText()))/100.0);
                Blender b1=new Blender(calories1,new Color(142, 229, 63), fruitvolume1);
                 arr.add(b1);
            case "banana":
            int fruitvolume2 = Integer.parseInt(fruitVolumeTextField.getText());
                double calories2 =  ((89*Integer.parseInt(fruitVolumeTextField.getText()))/100.0);
                Blender b2=new Blender(calories2,new Color(255, 255, 0), fruitvolume2);
                 arr.add(b2);
            case "apple":
                int fruitvolume3 = Integer.parseInt(fruitVolumeTextField.getText());
                double calories3 =  ((52*Integer.parseInt(fruitVolumeTextField.getText()))/100.0);
                Blender b3=new Blender(calories3,new Color(144, 238, 144) ,fruitvolume3);
                 arr.add(b3);
            case "orange":
                int fruitvolume4 = Integer.parseInt(fruitVolumeTextField.getText());
                double calories4 =  ((47*Integer.parseInt(fruitVolumeTextField.getText()))/100.0);
                Blender b4=new Blender(calories4,new Color(255, 165, 0), fruitvolume4);
                 arr.add(b4);
            default:
            break;
        }
        
    
    }*/
// TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed
//        int totalCalories = selectedFruit.getCalories() + selectedMilk.getCalories();
//        int totalVolume = selectedFruit.getVolume() + selectedMilk.getVolume();
//
//
//    private void populateComboBoxes() {
//        for (Ingredients fruit : fruits) {
//            fruitsComboBox.addItem(fruit.getName());
//        }
//        for (Ingredients milk : milks) {
//            milkComboBox.addItem(milk.getName());
//        }
//
//    }

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void pourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pourButtonActionPerformed
        // TODO add your handling code here:
        int cupVolume = 0;
        int numberOfCups = 0;
        if (smallRadioButton1.isSelected()) {
            cupVolume = smallCup;
        } else if (mediumRadioButton2.isSelected()) {
            cupVolume = mediumCup;
        } else if (largeRadioButton3.isSelected()) {
            cupVolume = largeCup;
        }
        if (cupVolume == 0) {
            JOptionPane.showMessageDialog(this, "Please select a cup size to continue! ");
        }
        while (blenderVolume >= cupVolume) {
            blenderVolume -= cupVolume;
            numberOfCups += 1;
            JOptionPane.showMessageDialog(this, "Poured: " + cupVolume + " ,Remaining: " + blenderVolume + " ,Number of poured cups: " + numberOfCups);
        }
        if (blenderVolume > 0 && blenderVolume < cupVolume) {
            cupVolume = blenderVolume;
            blenderVolume -= cupVolume;
            JOptionPane.showMessageDialog(this, "Poured: " + cupVolume + " ,Remaining: " + blenderVolume);

        }
    }//GEN-LAST:event_pourButtonActionPerformed

    private void jComboBoxFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFruitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFruitActionPerformed

    private void addSugarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSugarButtonActionPerformed
    int spoonsOfSugar = sugarSlider1.getValue();
    int sugarVolumePerSpoon = 5; // Assuming each spoon of sugar adds 5 mL
    int sugarCaloriesPerSpoon = 16; // Assuming each spoon of sugar adds 16 calories

    int sugarVolume = spoonsOfSugar * sugarVolumePerSpoon;
    int sugarCalories = spoonsOfSugar * sugarCaloriesPerSpoon;
    Sugar s = new Sugar("sugar", sugarVolume,sugarCalories);
        addedSugar.add(s);
    // Update total calories and volume
    totalCalories += sugarCalories;
    totalVolume += sugarVolume;

    // Display updated info
    displaySugar(); 
        // int sugarvolume = Integer.parseInt(addSugarButton.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_addSugarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCocktail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCocktail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCocktail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCocktail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCocktail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFruitsButton;
    private javax.swing.JButton addMilkButton;
    private javax.swing.JButton addSugarButton;
    private javax.swing.JList<String> blenderInfojList1;
    private javax.swing.ButtonGroup buttonGroupSize;
    private javax.swing.JPanel cupSizePanel;
    private javax.swing.JPanel fruitPanel;
    private javax.swing.JTextField fruitVolumeTextField;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxFruit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton largeRadioButton3;
    private javax.swing.JRadioButton mediumRadioButton2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JComboBox<String> milkComboBox;
    private javax.swing.JPanel milkPanel;
    private javax.swing.JTextField milkVolumeTextField;
    private javax.swing.JButton pourButton;
    private javax.swing.JRadioButton smallRadioButton1;
    private javax.swing.JSlider sugarSlider1;
    private javax.swing.JTextField sugarVolumeTextField;
    private javax.swing.JPanel sugatPanel;
    // End of variables declaration//GEN-END:variables
}
